# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c9ce9ddd3265a91cf50606b85408a107155433c644df2a5f62ac31b254ee001c57d254e28472291cc9e91ec4bbe147cd7db8ff1b8f46cdf68efc361c82d74d3

test:
  secret_key_base: a0b9aef40e96e71e88bad1b4cef124af658826dc1207588bc412e7fbadf1442ad881afe3550eb17bb791b66e78a032303c8df39dd248969913e7d5aa3b3a933f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
